#ifndef TOPICS_H
#define TOPICS_H

#include "FeniceEvoTopic.h"
#include "DataTopic.h"
#include "DataPrimaryTopic.h"
#include "DataSecondaryTopic.h"
#include "DataInverterTopic.h"
#include "DataGpsTopic.h"
#include "DataBrusaTopic.h"
#include "StatusTopic.h"
#include "StatusInfoTopic.h"
#include "StatusErrorTopic.h"
#include "StatusCanFrequenciesTopic.h"
#include "CommandTopic.h"
#include "CommandSendTopic.h"
#include "CommandResultTopic.h"
#include "FileTransactionAskTopic.h"
#include "FileTransactionAckTopic.h"
#include "FileTransactionTopic.h"
#include "FileTransactionBeginTopic.h"
#include "FileTransactionEndTopic.h"
#include "FileTransactionChunkTopic.h"
#include "ActionTopic.h"
#include "ActionTelemetryConfigTopic.h"
#include "ActionTelemetryConfigSetTopic.h"
#include "ActionTelemetryConfigGetTopic.h"
#include "ActionTelemetryConfigContentTopic.h"
#include "ActionSessionConfigTopic.h"
#include "ActionSessionConfigSetTopic.h"
#include "ActionSessionConfigGetTopic.h"
#include "ActionSessionConfigContentTopic.h"
#include "ActionCarConfigTopic.h"
#include "ActionCarConfigSetTopic.h"
#include "ActionCarConfigGetTopic.h"
#include "ActionCarConfigContentTopic.h"
#include "ActionConfigsSetTopic.h"
#include "ActionConfigsGetTopic.h"
#include "ActionConfigsContentTopic.h"
#include "ActionKillTelemetryTopic.h"
#include "ActionStartTelemetryTopic.h"
#include "ActionResetTelemetryTopic.h"
#include "ActionStopTelemetryTopic.h"
#include "ActionRawTopic.h"
#include "ActionResetLapCounterTopic.h"

namespace MQTTTopics {
 
	class FeniceEvoTopic;
	class DataTopic;
	class DataPrimaryTopic;
	class DataSecondaryTopic;
	class DataInverterTopic;
	class DataGpsTopic;
	class DataBrusaTopic;
	class StatusTopic;
	class StatusInfoTopic;
	class StatusErrorTopic;
	class StatusCanFrequenciesTopic;
	class CommandTopic;
	class CommandSendTopic;
	class CommandResultTopic;
	class FileTransactionAskTopic;
	class FileTransactionAckTopic;
	class FileTransactionTopic;
	class FileTransactionBeginTopic;
	class FileTransactionEndTopic;
	class FileTransactionChunkTopic;
	class ActionTopic;
	class ActionTelemetryConfigTopic;
	class ActionTelemetryConfigSetTopic;
	class ActionTelemetryConfigGetTopic;
	class ActionTelemetryConfigContentTopic;
	class ActionSessionConfigTopic;
	class ActionSessionConfigSetTopic;
	class ActionSessionConfigGetTopic;
	class ActionSessionConfigContentTopic;
	class ActionCarConfigTopic;
	class ActionCarConfigSetTopic;
	class ActionCarConfigGetTopic;
	class ActionCarConfigContentTopic;
	class ActionConfigsSetTopic;
	class ActionConfigsGetTopic;
	class ActionConfigsContentTopic;
	class ActionKillTelemetryTopic;
	class ActionStartTelemetryTopic;
	class ActionResetTelemetryTopic;
	class ActionStopTelemetryTopic;
	class ActionRawTopic;
	class ActionResetLapCounterTopic;

}// namespace MQTTTopics

#endif