#ifndef TOPICS_H
#define TOPICS_H

#include "FeniceEvoTopic.h"
#include "DataTopic.h"
#include "DataPrimaryTopic.h"
#include "DataSecondaryTopic.h"
#include "DataInverterTopic.h"
#include "DataGpsTopic.h"
#include "StatusTopic.h"
#include "StatusInfoTopic.h"
#include "StatusErrorTopic.h"
#include "StatusCanFrequenciesTopic.h"
#include "CommandTopic.h"
#include "CommandSendTopic.h"
#include "CommandResultTopic.h"
#include "FileTransactionAskTopic.h"
#include "FileTransactionAckTopic.h"
#include "FileTransactionTopic.h"
#include "FileTransactionBeginTopic.h"
#include "FileTransactionEndTopic.h"
#include "FileTransactionChunkTopic.h"
#include "ActionTopic.h"
#include "ActionSessionConfigTopic.h"
#include "ActionSessionConfigSetTopic.h"
#include "ActionSessionConfigGetTopic.h"
#include "ActionSessionConfigContentTopic.h"
#include "ActionTelemetryConfigTopic.h"
#include "ActionTelemetryConfigSetTopic.h"
#include "ActionTelemetryConfigGetTopic.h"
#include "ActionTelemetryConfigContentTopic.h"
#include "ActionCarSetupTopic.h"
#include "ActionCarSetupSetTopic.h"
#include "ActionCarSetupGetTopic.h"
#include "ActionCarSetupContentTopic.h"
#include "ActionConfigFileSetTopic.h"
#include "ActionConfigFileGetTopic.h"
#include "ActionConfigFileContentTopic.h"
#include "ActionKillTelemetryTopic.h"
#include "ActionStartTelemetryTopic.h"
#include "ActionStopTelemetryTopic.h"
#include "ActionRawTopic.h"
#include "ActionResetLapCounterTopic.h"

namespace MQTTTopics {
 
	class FeniceEvoTopic;
	class DataTopic;
	class DataPrimaryTopic;
	class DataSecondaryTopic;
	class DataInverterTopic;
	class DataGpsTopic;
	class StatusTopic;
	class StatusInfoTopic;
	class StatusErrorTopic;
	class StatusCanFrequenciesTopic;
	class CommandTopic;
	class CommandSendTopic;
	class CommandResultTopic;
	class FileTransactionAskTopic;
	class FileTransactionAckTopic;
	class FileTransactionTopic;
	class FileTransactionBeginTopic;
	class FileTransactionEndTopic;
	class FileTransactionChunkTopic;
	class ActionTopic;
	class ActionSessionConfigTopic;
	class ActionSessionConfigSetTopic;
	class ActionSessionConfigGetTopic;
	class ActionSessionConfigContentTopic;
	class ActionTelemetryConfigTopic;
	class ActionTelemetryConfigSetTopic;
	class ActionTelemetryConfigGetTopic;
	class ActionTelemetryConfigContentTopic;
	class ActionCarSetupTopic;
	class ActionCarSetupSetTopic;
	class ActionCarSetupGetTopic;
	class ActionCarSetupContentTopic;
	class ActionConfigFileSetTopic;
	class ActionConfigFileGetTopic;
	class ActionConfigFileContentTopic;
	class ActionKillTelemetryTopic;
	class ActionStartTelemetryTopic;
	class ActionStopTelemetryTopic;
	class ActionRawTopic;
	class ActionResetLapCounterTopic;

}// namespace MQTTTopics

#endif