#include "MQTTTopics.h"

const VehicleIdTopic MQTTTopics::vehicleIdTopic = VehicleIdTopic();
const DeviceIdTopic MQTTTopics::deviceIdTopic = DeviceIdTopic();
const DataTopic MQTTTopics::dataTopic = DataTopic();
const DataPrimaryTopic MQTTTopics::dataPrimaryTopic = DataPrimaryTopic();
const DataSecondaryTopic MQTTTopics::dataSecondaryTopic = DataSecondaryTopic();
const DataInverterTopic MQTTTopics::dataInverterTopic = DataInverterTopic();
const DataGpsTopic MQTTTopics::dataGpsTopic = DataGpsTopic();
const DataBrusaTopic MQTTTopics::dataBrusaTopic = DataBrusaTopic();
const StatusTopic MQTTTopics::statusTopic = StatusTopic();
const StatusInfoTopic MQTTTopics::statusInfoTopic = StatusInfoTopic();
const StatusErrorTopic MQTTTopics::statusErrorTopic = StatusErrorTopic();
const StatusCanFrequenciesTopic MQTTTopics::statusCanFrequenciesTopic = StatusCanFrequenciesTopic();
const CommandTopic MQTTTopics::commandTopic = CommandTopic();
const CommandSendTopic MQTTTopics::commandSendTopic = CommandSendTopic();
const CommandResultTopic MQTTTopics::commandResultTopic = CommandResultTopic();
const FileTransactionAskTopic MQTTTopics::fileTransactionAskTopic = FileTransactionAskTopic();
const FileTransactionAckTopic MQTTTopics::fileTransactionAckTopic = FileTransactionAckTopic();
const FileTransactionTopic MQTTTopics::fileTransactionTopic = FileTransactionTopic();
const FileTransactionBeginTopic MQTTTopics::fileTransactionBeginTopic = FileTransactionBeginTopic();
const FileTransactionEndTopic MQTTTopics::fileTransactionEndTopic = FileTransactionEndTopic();
const FileTransactionChunkTopic MQTTTopics::fileTransactionChunkTopic = FileTransactionChunkTopic();
const ActionTopic MQTTTopics::actionTopic = ActionTopic();
const ActionTelemetryConfigTopic MQTTTopics::actionTelemetryConfigTopic = ActionTelemetryConfigTopic();
const ActionTelemetryConfigSetTopic MQTTTopics::actionTelemetryConfigSetTopic = ActionTelemetryConfigSetTopic();
const ActionTelemetryConfigGetTopic MQTTTopics::actionTelemetryConfigGetTopic = ActionTelemetryConfigGetTopic();
const ActionTelemetryConfigContentTopic MQTTTopics::actionTelemetryConfigContentTopic = ActionTelemetryConfigContentTopic();
const ActionSessionConfigTopic MQTTTopics::actionSessionConfigTopic = ActionSessionConfigTopic();
const ActionSessionConfigSetTopic MQTTTopics::actionSessionConfigSetTopic = ActionSessionConfigSetTopic();
const ActionSessionConfigGetTopic MQTTTopics::actionSessionConfigGetTopic = ActionSessionConfigGetTopic();
const ActionSessionConfigContentTopic MQTTTopics::actionSessionConfigContentTopic = ActionSessionConfigContentTopic();
const ActionCarConfigTopic MQTTTopics::actionCarConfigTopic = ActionCarConfigTopic();
const ActionCarConfigSetTopic MQTTTopics::actionCarConfigSetTopic = ActionCarConfigSetTopic();
const ActionCarConfigGetTopic MQTTTopics::actionCarConfigGetTopic = ActionCarConfigGetTopic();
const ActionCarConfigContentTopic MQTTTopics::actionCarConfigContentTopic = ActionCarConfigContentTopic();
const ActionConfigsSetTopic MQTTTopics::actionConfigsSetTopic = ActionConfigsSetTopic();
const ActionConfigsGetTopic MQTTTopics::actionConfigsGetTopic = ActionConfigsGetTopic();
const ActionConfigsContentTopic MQTTTopics::actionConfigsContentTopic = ActionConfigsContentTopic();
const ActionKillTopic MQTTTopics::actionKillTopic = ActionKillTopic();
const ActionStartTopic MQTTTopics::actionStartTopic = ActionStartTopic();
const ActionResetTopic MQTTTopics::actionResetTopic = ActionResetTopic();
const ActionStopTopic MQTTTopics::actionStopTopic = ActionStopTopic();
const ActionPrechargeTopic MQTTTopics::actionPrechargeTopic = ActionPrechargeTopic();
const ActionBalanceTopic MQTTTopics::actionBalanceTopic = ActionBalanceTopic();
const ActionStopBalance MQTTTopics::actionStopBalance = ActionStopBalance();
const ActionChargeTopic MQTTTopics::actionChargeTopic = ActionChargeTopic();
const ActionStopCharge MQTTTopics::actionStopCharge = ActionStopCharge();
const ActionRawTopic MQTTTopics::actionRawTopic = ActionRawTopic();
const ActionResetLapCounterTopic MQTTTopics::actionResetLapCounterTopic = ActionResetLapCounterTopic();


std::vector<TopicString> MQTTTopics::GetSubscribeTopics(unsigned int role) {
    std::vector<TopicString> ret;

    switch(role){

		case 0:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 1:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 2:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 3:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 4:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 128:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 129:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

    }

    return ret;
}

std::vector<TopicString> MQTTTopics::GetPublishTopics(unsigned int role) {
    std::vector<TopicString> ret;

        switch(role){

		case 0:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 1:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 2:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 3:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 4:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 128:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

		case 129:
			ret.push_back(vehicleIdTopic.get("+"));
			ret.push_back(deviceIdTopic.get("+", "+"));
			ret.push_back(dataTopic.get("+", "+"));
			ret.push_back(dataPrimaryTopic.get("+", "+"));
			ret.push_back(dataSecondaryTopic.get("+", "+"));
			ret.push_back(dataInverterTopic.get("+", "+"));
			ret.push_back(dataGpsTopic.get("+", "+"));
			ret.push_back(dataBrusaTopic.get("+", "+"));
			ret.push_back(statusTopic.get("+", "+"));
			ret.push_back(statusInfoTopic.get("+", "+"));
			ret.push_back(statusErrorTopic.get("+", "+"));
			ret.push_back(statusCanFrequenciesTopic.get("+", "+"));
			ret.push_back(commandTopic.get("+", "+"));
			ret.push_back(commandSendTopic.get("+", "+"));
			ret.push_back(commandResultTopic.get("+", "+"));
			ret.push_back(fileTransactionAskTopic.get("+", "+"));
			ret.push_back(fileTransactionAckTopic.get("+", "+"));
			ret.push_back(fileTransactionTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionBeginTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionEndTopic.get("+", "+", "+"));
			ret.push_back(fileTransactionChunkTopic.get("+", "+", "+"));
			ret.push_back(actionTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigSetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigGetTopic.get("+", "+"));
			ret.push_back(actionTelemetryConfigContentTopic.get("+", "+"));
			ret.push_back(actionSessionConfigTopic.get("+", "+"));
			ret.push_back(actionSessionConfigSetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigGetTopic.get("+", "+"));
			ret.push_back(actionSessionConfigContentTopic.get("+", "+"));
			ret.push_back(actionCarConfigTopic.get("+", "+"));
			ret.push_back(actionCarConfigSetTopic.get("+", "+"));
			ret.push_back(actionCarConfigGetTopic.get("+", "+"));
			ret.push_back(actionCarConfigContentTopic.get("+", "+"));
			ret.push_back(actionConfigsSetTopic.get("+", "+"));
			ret.push_back(actionConfigsGetTopic.get("+", "+"));
			ret.push_back(actionConfigsContentTopic.get("+", "+"));
			ret.push_back(actionKillTopic.get("+", "+"));
			ret.push_back(actionStartTopic.get("+", "+"));
			ret.push_back(actionResetTopic.get("+", "+"));
			ret.push_back(actionStopTopic.get("+", "+"));
			ret.push_back(actionPrechargeTopic.get("+", "+"));
			ret.push_back(actionBalanceTopic.get("+", "+"));
			ret.push_back(actionStopBalance.get("+", "+"));
			ret.push_back(actionChargeTopic.get("+", "+"));
			ret.push_back(actionStopCharge.get("+", "+"));
			ret.push_back(actionRawTopic.get("+", "+"));
			ret.push_back(actionResetLapCounterTopic.get("+", "+"));
			break;

    }

    return ret;
}
